Sprint03 us28 accueil services
WildCodeSchool/orleans-0219-php-grand-hotel pull request #21
Opened 2019-04-23 15:57 UTC by yohanntemplier

2019-04-23 16:04 UTC, vangjeannette approved these changes

2019-04-24 07:27 UTC, sblondeau requested changes

2019-04-24 07:27 UTC, sblondeau commented on src/View/Home/HomeServices.html.twig
> +                <p><img id="americanexpress" src="/assets/images/services/amex.png" alt="image d'american express" class="icone"/>Américan express accépté</p>
par d'accent en anglais (sur American)
"acceptée"

2019-04-24 07:27 UTC, sblondeau commented on src/View/Home/HomeServices.html.twig
> +                <p><img id="chequevancance" src="/assets/images/services/chequevacances.png" alt="image de cheque vacances" class="icone"/>Chêques vancances accéptés</p>
Chèques vacances acceptés (attention à l'orthographe...)

2019-04-24 09:22 UTC, sblondeau approved these changes

2019-04-24 09:22 UTC, merged