finalisation de la page seminaire statique version 1
WildCodeSchool/orleans-0219-php-grand-hotel pull request #25
Opened 2019-04-24 11:24 UTC by vangjeannette

2019-04-24 11:38 UTC, 01Andre commented
OK

2019-04-24 11:40 UTC, 01Andre approved these changes

2019-04-24 15:36 UTC, sblondeau requested changes
l'image est trop grosse

- soit vous rendez la page dynamique et dans ce cas il faut le fichier manager et la table (avec le nom en anglais), et la requete qui va bien dans le controleur
- soit tu le mets en statique (je pense que vous partez la dessus) et dans ce cas il faut enlever le fichier manager de la PR

2019-04-24 15:36 UTC, sblondeau commented on src/Controller/SeminaireController.php
> +class SeminaireController extends AbstractController
je pense que la bonne traduction est "seminar" (valide peut-être avec Casey) mais définitivement pas "Seminaire" ;-)

2019-04-24 15:36 UTC, sblondeau commented on src/Model/SeminaireManager.php
> +    const TABLE = 'seminaire';
a modif partout bien entendu, meme le nom de la table

2019-04-25 08:57 UTC, 01Andre approved these changes

2019-04-25 14:15 UTC, sblondeau approved these changes

2019-04-25 14:15 UTC, merged