Sprint03 fix
WildCodeSchool/orleans-0219-php-grand-hotel pull request #31
Opened 2019-04-26 08:27 UTC by yohanntemplier

2019-04-26 08:30 UTC, vangjeannette approved these changes

2019-04-26 12:04 UTC, sblondeau requested changes
toutes les images > 100ko à redimensionner (y en a 2 là). De plus le brickwall n'est-il pas à virer ?

2019-04-26 12:04 UTC, sblondeau commented on src/View/_navbar.html.twig
> +                    <button type="button" class="btn btn-resa" style="position: absolute; right: 0;"><a class="navbar-brand-resa" href="https://www.contact-hotel.com/hotel-france/1753/grand-hotel-orl
style inline à enlever !

2019-04-28 21:45 UTC, sblondeau approved these changes

2019-04-28 21:45 UTC, merged