Sprint03 us4 room index
WildCodeSchool/orleans-0219-php-grand-hotel pull request #33
Opened 2019-04-26 20:34 UTC by 01Andre

Je m'explique : la PR antérieure incluait 3 fichiers qui n'avaient rien à faire dans cette US. Donc j'ai créé une nouvelle branche pour avoir une PR propre.
Ensuite, il y avait des corrections à faire sur la PR antérieure : 
-dégager les {{dump(rooms)}} et tableaux dans le controller;
-dégager une key qui ne servait à rien dans le controller;
-dégager les fonctions inutiles ou redondantes dans le roomManager, et utiliser la fonction "native" à la place dans le home controller.
Elles sont faites.

2019-04-27 17:31 UTC, vangjeannette approved these changes

2019-04-28 21:48 UTC, sblondeau requested changes

2019-04-28 21:48 UTC, sblondeau commented on src/Model/RoomManager.php
> +            "SELECT photo_name FROM room_photo JOIN room ON room_photo.room_id = room.id
logiquement tu n'as pas besoin de la jointure là si tu ne recupère que le photo_name a partir d'un room_id ?
un SELECT photo_name FORM room_photo WHERE room.id=$roomId; est suffisant ?

2019-04-29 07:43 UTC, 01Andre commented on src/Model/RoomManager.php
> +            "SELECT photo_name FROM room_photo JOIN room ON room_photo.room_id = room.id
OK

2019-04-29 10:28 UTC, sblondeau approved these changes

2019-04-29 10:28 UTC, merged