création page accueil admin
WildCodeSchool/orleans-0219-php-grand-hotel pull request #34
Opened 2019-04-27 06:31 UTC by 01Andre

2019-04-27 17:03 UTC, vangjeannette approved these changes

2019-04-28 21:50 UTC, sblondeau requested changes

2019-04-28 21:50 UTC, sblondeau commented on src/View/layoutAdmin.html.twig
> +<!doctype html>
doit étendre layout qui lui est commun à layoutVisitor ET layoutAdmin

2019-04-29 07:53 UTC, 01Andre commented on src/View/layoutAdmin.html.twig
> +<!doctype html>
OK

2019-04-29 10:20 UTC, sblondeau requested changes

2019-04-29 10:20 UTC, sblondeau commented on src/View/layoutAdmin.html.twig
> +<!doctype html>
non car ton layout possède déjà là partie doctype, ça ne doit pas etre répété ici, c'est justement l'intéret d'aovir un layout de base

2019-04-29 13:16 UTC, 01Andre commented on src/View/layoutAdmin.html.twig
> +<!doctype html>
OK

2019-04-29 20:16 UTC, sblondeau approved these changes

2019-04-29 20:35 UTC, 01Andre commented
OK, conflits gérés.

2019-04-29 20:51 UTC, merged