Sprint03 us21 w epage
WildCodeSchool/orleans-0219-php-grand-hotel pull request #39
Opened 2019-04-29 14:44 UTC by yohanntemplier

2019-04-29 14:50 UTC, 01Andre approved these changes

2019-04-29 20:20 UTC, sblondeau requested changes
si c'est administrable, les images, une fois encore, ne doivent pas etre versionnées !
donc les retirer avec un git rm --cached et ajouter dans le .gitignore le dossier

2019-04-30 05:22 UTC, yohanntemplier commented
Non, on a pas trop le temps de le faire administrable. C'est les photos sont versionnées. La page est statique.

2019-04-30 06:58 UTC, sblondeau requested changes
dans ce cas, les images  doivent être réduites, 100Ko max par photo
passe les en webp par ex

2019-04-30 08:11 UTC, sblondeau approved these changes

2019-04-30 08:11 UTC, merged