Accueil carroussel
WildCodeSchool/orleans-0219-php-grand-hotel pull request #5
Opened 2019-04-15 13:03 UTC by yohanntemplier

2019-04-15 13:09 UTC, 01Andre approved these changes
OK!

2019-04-15 13:30 UTC, open-it requested changes

2019-04-15 13:30 UTC, open-it commented on src/View/Item/_HomeCarroussel.html.twig
> +<div class="container">
Le carroussel ne devrait pas être dans le dossier Item

2019-04-15 13:30 UTC, open-it commented on src/View/layoutVisitor.html.twig
>      {% include('/Item/_footer.html.twig') %}
le footer aussi d'ailleurs

2019-04-15 13:50 UTC, 01Andre approved these changes
Parfait!

2019-04-15 13:56 UTC, open-it requested changes

2019-04-15 13:56 UTC, open-it commented on src/View/layoutVisitor.html.twig
> +    {% include('/Home/_footer.html.twig') %}
je ne pense pas que le footer soit présent que dans la Home ?

2019-04-15 14:08 UTC, 01Andre approved these changes
OK!

2019-04-16 07:57 UTC, sblondeau requested changes
la branche devrait etre nommée selon la syntaxe qu'on avait donné SXXUSXX_feature
afin qu'on puisse facilement se référer facilement à la US correspondante

toutes les images de la galeries sont administrable/uploadées normalement non ? du coup ce dossier ne devrait pas etre versionné et je ne devrait pas retrouver les images sur github

2019-04-16 07:57 UTC, sblondeau commented on src/View/layoutVisitor.html.twig
> +    {% include('/Home/_HomeCarroussel.html.twig') %}
le home carroussel n'est que sur la homepage non ? donc on ne devrait pas l'inclure dans le layoutVisitor mais seulement sur la page Home/index.html.twig

2019-04-16 08:17 UTC, closed without merging