Pagechambres
WildCodeSchool/orleans-0219-php-grand-hotel pull request #6
Opened 2019-04-15 14:41 UTC by 01Andre

Je suis  PO.

2019-04-15 15:46 UTC, yohanntemplier approved these changes

2019-04-16 08:13 UTC, sblondeau requested changes
si les images sont administrable/uploadable (et je crois que c'est le cas) on ne devrait pas les retrouver ici

2019-04-16 08:13 UTC, sblondeau commented on src/Controller/HomeController.php
> +        $itemManager = new ItemManager();
je ne devrais plus voir de mention de "Item"  si je suis dans le HomeController non ?

2019-04-16 08:13 UTC, sblondeau commented on src/Controller/RoomsController.php
> +        $rooms = $roomsManager->selectAllDoubleJoin('room_id', 'id', 'room_id');
je ne comprends meme pas ce que tu essaies de faire :D 
ici tu devrais juste avoir un $roomManager->selecAll(), vu que ta page affiche toutes les rooms.

2019-04-16 08:13 UTC, sblondeau commented on src/Controller/RoomsController.php
> +        $roomsPhotosManager = new RoomsManager();
si tu dois faire deux requetes d'un meme manager, tu n'as pas à le reinstancier

2019-04-16 08:13 UTC, sblondeau commented on src/Controller/RoomsController.php
> +            unset($caracteristics[$i]['id']);
je ne comprend pas tes unsets

2019-04-16 08:13 UTC, sblondeau commented on src/Model/AbstractManager.php
> +    public function __construct(string $table, string $tableToJoin = '', string $secondTableToJoin = '')
tu n'as pas à changer la signature de ce controller
si tu as des paramètres, ils seront dans tes méthodes. Et en plus ton nommage est tel que je ne comprends rien à ce que tu cherches à faire ;-) à revoir

2019-04-16 08:13 UTC, sblondeau commented on src/Model/AbstractManager.php
> +    public function selectAllDoubleJoin(string $foreignKey, string $primaryKey, string $secondForeignKey): array
ah... je pense comprendre ce que tu veux faire. Mais non :D car tu fais comment quand tu as une requete qui demande 5 jointures ? tu fait un selectAllFiveJoin ? 
crée les méthodes particulière de jointures dans chaque Manager selon les besoins et n'essaie pas de faire des méthodes génériques comme ça qui sont vite ingérables

2019-04-16 08:13 UTC, sblondeau commented on src/Model/RoomsManager.php
> +    const SECONDTABLETOJOIN = 'room_caracteristic';
encore une fois, tout ce qui est TABLETOJOIN et SECONDTABLE à virer

2019-04-16 08:13 UTC, sblondeau commented on src/View/Rooms/index.html.twig
> +                                <div class="carousel-item active">
non, il faudrait dans ce cas que tu aies un tableau de photos sur lequel tu boucles. Tu ne devrais pas répéter N fois tes div class="carousel-item"

2019-04-16 08:13 UTC, sblondeau commented on src/View/Rooms/index.html.twig
> +                {% if key is not odd %}
toute cette partie odd/even ne devrait pas etre répéter. Gère le avec des classes CSS particulières (ou direct en CSS tu peux le détecter aussi)

2019-04-16 09:10 UTC, 01Andre commented on src/Controller/HomeController.php
> +        $itemManager = new ItemManager();
OK done

2019-04-16 09:39 UTC, 01Andre commented on src/Controller/RoomsController.php
> +        $rooms = $roomsManager->selectAllDoubleJoin('room_id', 'id', 'room_id');
OK

2019-04-16 09:42 UTC, 01Andre commented on src/Controller/RoomsController.php
> +        $roomsPhotosManager = new RoomsManager();
OK

2019-04-16 09:43 UTC, 01Andre commented on src/Controller/RoomsController.php
> +            unset($caracteristics[$i]['id']);
OK. Je faisais une fonction générique, donc je devais garder un select all générique. Maintenant que la fonction est dans le room manager, je l'ai personnalisée, et n'ai plus besoin de unset

2019-04-16 09:48 UTC, 01Andre commented on src/Model/AbstractManager.php
> +    public function __construct(string $table, string $tableToJoin = '', string $secondTableToJoin = '')
OK. puisque tout a été rapatrié

2019-04-16 09:49 UTC, 01Andre commented on src/Model/RoomsManager.php
> +    const SECONDTABLETOJOIN = 'room_caracteristic';
fait

2019-04-16 11:52 UTC, 01Andre commented on src/View/Rooms/index.html.twig
> +                {% if key is not odd %}
OK, j'ai enlevé 2 des 3 carousel

2019-04-16 11:52 UTC, 01Andre commented on src/Model/AbstractManager.php
> +    public function selectAllDoubleJoin(string $foreignKey, string $primaryKey, string $secondForeignKey): array
ok fait

2019-04-16 12:11 UTC, 01Andre commented on src/View/Rooms/index.html.twig
> +                                <div class="carousel-item active">
OK

2019-04-16 12:14 UTC, closed without merging